#lang sicp

#| Exercise 1.15: The sine of an angle (speciﬁed in radians)
can be computed by making use of the approximation sin x ≈ x
if x is suﬃciently small, and the trigonometric identity
sine x. sin x = 3 sin − 4 sin3
3
3
to reduce the size of the argument of sin. (For purposes of
this exercise an angle is considered “suﬃciently small” if its
magnitude is not greater than 0.1 radians.) ese ideas are
incorporated in the following procedures: |#

(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
    angle
    (p (sine (/ angle 3.0)))))


#| a. How many times is the procedure p applied when (sine
12.15) is evaluated?

ANSWER: 

The process will eveolve according to the following:

(sine 12.15)
(p (sine 4.05))
(p (p (sine 1.35)))
(p (p (p (sine 0.45))))
(p (p (p (p (sine 0.15)))))
(p (p (p (p (p (sine 0.05))))))

At this point, the angle is smaller than 0.1 and the process
starts computing p. The procedure p is applied five times in
total.


b. What is the order of growth in space and number of
steps (as a function of a) used by the process generated
by the sine procedure when (sine a) is evaluated? 

The order of growth for the process generated by the sine
procedure will be given by n, the number of times p is applied
before reaching the base case (where the angle is less than
0.1):

a / 3^n <= 0.1
a <= 0.1 - 3^n
10a <= 3^n
n >= log_3(10a)
n >= log_3(a) + log_3(10)

Therefore, the process is Θ(log(a)). |#